// types.ts

export interface ProductVariantOptionValue {
  value: string;
  // Future extension: hex code for color swatches, etc.
}

export interface ProductVariantOption {
  name: string; // e.g., "Size", "Color"
  values: ProductVariantOptionValue[];
}

export interface ProductVariant {
  id: string; // Will be a UUID generated by the database
  productId: string;
  name: string; // e.g., "Small / Red"
  price: number;
  sku: string;
  gtin?: string | null;
  weight: number; // in grams
  stock: number;
  imageUrls: string[]; // Specific images for this variant
  options: Record<string, string>; // e.g., { "Size": "S", "Color": "Red" }
}


export interface Product {
  id: string;
  name: string;
  category: string;
  imageUrls: string[]; // Main product images
  videoUrl: string | null;
  longDescription: string;
  createdAt?: string;
  // Variant structure
  variantOptions: ProductVariantOption[];
  variants: ProductVariant[];
}

export interface CartItem {
  cartItemId: string; // A unique ID for the cart item, e.g., `${product.id}-${variant.id}`
  product: Pick<Product, 'id' | 'name' | 'category'>; // Basic product info
  variant: ProductVariant;
  quantity: number;
}


export interface Location {
  id: string | number;
  name: string;
}

export interface Province extends Location {}
export interface City extends Location {}
export interface District extends Location {}
export interface Subdistrict extends Location {}

export interface ShippingOption {
  code: string;
  name: string;
  service: string;
  description: string;
  cost: number;
  etd: string; // Estimated time of delivery
}

export interface CustomerDetails {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  address: string;
  postalCode: string;
  province: { id: string; name: string };
  city: { id: string; name: string };
  district: { id: string; name: string };
  subdistrict: { id: string; name: string } | null;
}

// Detailed types for fetching from the database for the Admin Panel
export interface Customer {
  id: string;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
}

export interface OrderItemWithProduct {
  quantity: number;
  price: number;
  products: Pick<Product, 'id' | 'name'> & { product_variants: Pick<ProductVariant, 'id' | 'name'> | null } | null;
}

export type OrderStatus = 'pending_payment' | 'paid' | 'shipped' | 'failed' | 'delivered';

export interface FullOrder {
  id: string;
  order_number: string;
  status: OrderStatus;
  total_amount: number;
  created_at: string;
  shipping_provider: string;
  shipping_service: string;
  awb_number: string | null; // Added for Komerce AWB
  customers: Customer | null;
  order_items: OrderItemWithProduct[];
}

// Meta Marketing API Types
export interface MetaAdAccount {
  id: string;
  name: string;
}

export interface MetaCampaign {
  id: string;
  name: string;
  status: 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
  objective: string;
  insights?: MetaCampaignInsights; // Optional, to be merged later
}

export interface MetaCampaignInsights {
  spend: string;
  impressions: string;
  clicks: string;
  cpc: string; // Cost per click
  ctr: string; // Click-through rate
}

export interface ContactFormData {
  name: string;
  email: string;
  subject: string;
  message: string;
}
